-- Copyright (c) 2017 CCS/GMRV/UPM/URJC.
-- 
-- Author: Juan P. Brito <juanpedro.brito@upm.es>
-- 
-- This library is free software; you can redistribute it and/or modify it under
-- the terms of the GNU Lesser General Public License version 3.0 as published
-- by the Free Software Foundation.
-- 
-- This library is distributed in the hope that it will be useful, but WITHOUT
-- ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
-- FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
-- details.
-- 
-- You should have received a copy of the GNU Lesser General Public License
-- along with this library; if not, write to the Free Software Foundation, Inc.,
-- 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

CREATE DATABASE IF NOT EXISTS `ColVizDB` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `ColVizDB`;

CREATE TABLE USERS (
    ID INT(11) NOT NULL AUTO_INCREMENT,	

    NAME VARCHAR(100) DEFAULT NULL,
	
    SURNAME VARCHAR(100) DEFAULT NULL,
    
    EMAIL VARCHAR(100) DEFAULT NULL,
	
    USERPASSWORD VARCHAR(100) DEFAULT NULL,

    PRIMARY KEY (ID)
); 

CREATE TABLE TYPESOFEXPERIMENTS(
    ID INT(11) NOT NULL AUTO_INCREMENT,	

    TYPEOFEXPERIMENT VARCHAR(300) DEFAULT NULL,    

    PRIMARY KEY (ID)
); 


CREATE TABLE EXPERIMENTS (
    ID INT(11) NOT NULL AUTO_INCREMENT,	

    DESCRIPTION VARCHAR(3000) DEFAULT NULL,    

    TYPESOFEXPERIMENTSID INT(11) NOT NULL,
    
    PRIMARY KEY (ID)
);
 
ALTER TABLE EXPERIMENTS ADD FOREIGN KEY (TYPESOFEXPERIMENTSID) REFERENCES TYPESOFEXPERIMENTS(ID);

CREATE TABLE SESSIONS (
    ID int(11) NOT NULL AUTO_INCREMENT,	

    DESCRIPTION TEXT DEFAULT NULL,    

    USERID  int(11) NOT NULL,

    EXPERIMENTID int(11) NOT NULL,
    
    PRIMARY KEY (ID)
); 

ALTER TABLE SESSIONS ADD FOREIGN KEY (EXPERIMENTID) REFERENCES EXPERIMENTS(ID);

CREATE TABLE DIALOGS (
    ID INT(11) NOT NULL AUTO_INCREMENT,	

    MESSAGE VARCHAR(3000) DEFAULT NULL,    

    USERID int(11) NOT NULL,
    
    SESSIONID int(11) NOT NULL,	
    
    MESSAGETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP  
    ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (ID)
); 

ALTER TABLE DIALOGS ADD FOREIGN KEY (USERID) REFERENCES USERS(ID);
ALTER TABLE DIALOGS ADD FOREIGN KEY (SESSIONID) REFERENCES SESSIONS(ID);

CREATE TABLE DATAEXPERIMENT (
    ID INT(11) NOT NULL AUTO_INCREMENT,	

    EXPERIMENTID INT(11) NOT NULL,
    
    NOTEEXPERIMENT VARCHAR(3000) DEFAULT NULL,    

    PRIMARY KEY (ID)
);

ALTER TABLE DATAEXPERIMENT ADD FOREIGN KEY (EXPERIMENTID) REFERENCES EXPERIMENTS(ID);
